const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export {metadata};

function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
};

export default RootLayout;