import SocketComponent from '@/scripts/socket-app'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="/socket.io/socket.io.js"></script>
      </head>
      <body className={inter.className}>
        {children}
        <script src="@/scripts/socket-app.js"/>
      </body>
    </html>
  )
}
